platform :ios, '5.0'
pod 'AFNetworking', '~> 1.2.0'
pod 'SDURLCache', '~> 1.2'
pod 'NVSlideMenuController', '~> 1.4.3'
pod 'GoogleAnalytics-iOS-SDK', '~> 2.0beta4'
pod 'MDCParallaxView', '~> 0.1.2'
pod 'MBProgressHUD', '~> 0.6'
pod 'STTweetLabel', '~> 2.2.2'
pod 'PHFRefreshControl', '~> 1.0.0'
pod 'SDSegmentedControl', '~> 1.0.1'
